# Model arguments
model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct
teacher_model_name_or_path: Qwen/Qwen2.5-VL-3B-Instruct

# viscot_rand.yaml or gqa_rand.yaml
train_dataset: dataset_configs/gqa_rand.yaml
torch_dtype: bfloat16
target_size:
  - 224
  - 224
projector_enable: false
g_raw_enable: false
token_sort_enable: true

#Training arguments
lambda_kd: 1.0
lambda_distortion: 1.0
lambda_rate: 0.3
target_rate: 0.25

# default training arguments
gradient_checkpointing: true
output_dir: output/qwen2_5_3b_pato
bf16: true
fp16: false
report_to: none
attn_implementation: flash_attention_2
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1e-4
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.1
remove_unused_columns: false
logging_steps: 10
save_steps: 500